### PR TITLE
fix: unused assigns of list arguments

### LINKED ISSUE #1308: Confusing behavior around derive & lists?
While writing https://github.com/prql/prql/issues/648#issuecomment-1360070136, I found a case where I think we should raise an error:

```elm
from employees
derive x = [foo]
```

Currently we add `foo`, but just drop the alias:

```sql
SELECT
  *,
  foo   # No x!
FROM
  employees
```

### PR DESCRIPTION
**Pull request by aljazerzen**
Closes #1308

### CODE REVIEW

File: prql-compiler/src/test.rs [hunk 1]
```diff
@@ -1939,6 +1939,25 @@ fn test_filter_and_select_changed_alias() {
...
+    select n = [account.name]
+    "###).unwrap_err(), @r###"
+    Error:
+    ╭─[:3:12]
+    │
+    3 │     select n = [account.name]
+    ·            ─────────┬────────
+    ·                     ╰────────── unexpected assign to `n`
+    ·
+    · Help: move assign into the list: `[n = ...]`
```
Comment (max-sixty) [inline prql-compiler/src/test.rs:1956]: That's really great! Both the error message and the test!
