### PR TITLE
fix: playground

### LINKED ISSUE #1309: Playground "copy to clipboard" no longer works
I'm just getting `undefined` hitting the clipboard. I tried on Firefox & Chrome

### PR DESCRIPTION
**Pull request by aljazerzen**
Closes #1309

### CODE REVIEW

File: prql-compiler/src/error.rs [hunk 1]
```diff
@@ -24,8 +24,8 @@ pub struct Error {
 
 /// Location within the source file.
 /// Tuples contain:
-/// - line number (1-based),
-/// - column number within that line (1-based),
+/// - line number (0-based),
```
Comment (max-sixty) [inline prql-compiler/src/error.rs:27]: Should we change this to 1-based? It seems quite non-standard, no?

(as ever — not saying you have to do it)

**Comment by max-sixty** [comment]
Thanks a lot
