### PR TITLE
Resolve all variable names

### LINKED ISSUE #222: Function vs. identifier namespaces
Something PRQL does that's distinct from general purpose languages — and common with SQL — is allow identifiers to refer to data; e.g. PRQL's `from a | select [b, c]` would generally be something like `load("a")["b", "c"]`, with quotes around the data references.

One disadvantage of PRQL's approach is it's difficult to mix identifiers and function names. SQL does this quite well, at the cost of no abstractions; for example:

```sql
select
  limit_date as date,             # Create a column named `data`
  date('2021-01-01') as start,    # Use `date` as a function
  count(*) as count               # Create a column name `count` without interfering with the function
from data
group by 1
having count > 0
```

But PRQL gets confused by:

```elm
from data
aggregate [count: count foo] by:limit_date
filter count > 0                 # What does `count` refer to here?
```

`count` refers to the function, rather than the column, so this raises an error.

I think that's fairly reasonable, but it leads to a few priorities:
- Good error messages — if someone uses `count` like this, we should say "you have an assignment above named `count`, but it refers to a function here", and not "wrong number of arguments for `count`".
- Additions to the stdlib become backward-incompatible, since they might conflict with existing column names
- We should add documentation for avoiding this. One workaround is using an s-string; i.e. `s'count'` always compiles into `count` in SQL. Possibly there's a language addition that allows a more specific way of being explicit, without giving up our treasured approach of allowing identifier for data references.

### LINKED ISSUE #247: Reference to the current pipeline
## Problem 

So when writing PRQL, at each line you have access to scope of columns, some of which belong to actual tables, some are aliases and some are columns of CTEs. The problem is that you cannot reference the latter!

See the example:

```
from salaries
aggregate by:[emp_no] [
  emp_salary: average salary
]
join dept_emp [dept_emp.emp_no = emp_no]
```

produces:
```
WITH table_0 AS (
  SELECT
    emp_no,
    AVG(salary) AS emp_salary
  FROM
    salaries
  GROUP BY
    emp_no
),
table_1 AS (
  SELECT
    *
  FROM
    table_0
    JOIN dept_emp ON dept_emp.emp_no = emp_no
)
SELECT
  *
FROM
  table_1
```

Executing this query in PG returns:
```
ERROR:  column reference "emp_no" is ambiguous
LINE 15:     JOIN dept_emp ON dept_emp.emp_no = emp_no
                                                ^
```

`emp_no` could reference `table_0.emp_no` or `dept_emp.emp_no`. We want to reference `table_0`, which we currently can, if we use:

    join dept_emp [dept_emp.emp_no = table_0.emp_no]

but this is an inconsistent hack, that will not work once we prefix the query with some other pipelines or aggregation.

## Proposal

Instead I propose that we introduce `$`, a table reference that points to the *last CTE*. In the query would be:

```
join dept_emp [dept_emp.emp_no = $.emp_no]
```

Alternatively, we could just use `.emp_no`, but I am against that, because it is not explicit enough.

### PR DESCRIPTION
**Pull request by aljazerzen**
Changes:

- Resolver will throw errors if there are variables it cannot resolve.
  (it will take into account unknown table fields, so `from employees | select first_name` will still work)

- Resolved AST will contain full table names. This is required because of this use case:

  ```
  from companies
  select [name, company_no]
  join employees [company_no]
  ```
  What one would expect here is:
  ```
  SELECT name, company_no, employees.* 
  FROM companies JOIN employees USING(company_no)
  ```
  ...but what if employees also have column `name`? Only reference `name` would be ambigious. Which means full-quailified table names are required:
  ```
  SELECT companies.name, company_no, employees.* 
  FROM companies JOIN employees USING(company_no)
  ```

  We could only add full tables names when there are multiple tables in scope, but due to non-sequential nature of SQL SELECTs, this is quite an effort.

- table names will be corrected between splits, which closes #247
- ambiguous references will throw an error, which closes #222
- `table.*` is now allowed. This is useful in such cases:
  ```
  from employees
  join salaries [emp_no]
  select [emplyees.*, salary]
  ```

### CODE REVIEW

File: prql/src/ast_fold.rs [hunk 1]
```diff
@@ -31,7 +31,7 @@ pub trait AstFold {
     fn fold_pipeline(&mut self, pipeline: Vec<Transform>) -> Result<Vec<Transform>> {
         pipeline
             .into_iter()
-            .map(|t| self.fold_transformation(t))
+            .map(|t| self.fold_transform(t))
```
Comment (max-sixty) [inline prql/src/ast_fold.rs:34]: Shall we call these `transforms` everywhere? I'm up for it if you are...

File: prql/src/semantic/context.rs [hunk 2]
```diff
@@ -3,33 +3,43 @@ use enum_as_inner::EnumAsInner;
...
 /// Scope within which we can reference variables, functions and tables
 /// Provides fast lookups for different names.
 #[derive(Debug, Default, Serialize, Deserialize, Clone)]
 pub struct Context {
     /// current table columns (result of last pipeline)
-    pub(super) table: Vec<TableColumn>,
+    pub(super) frame: Vec<TableColumn>,
+
+    /// For each namespace (table), a map from column names to their definitions
+    /// "$" is namespace of variables not belonging to any table (aliased, join using)
```
Comment (max-sixty) [inline prql/src/semantic/context.rs:22]: It'd also be fine to use an `Enum` for this, but this is ofc fine

File: prql/src/semantic/materializer.rs [hunk 3]
```diff
@@ -357,10 +419,10 @@ aggregate [
         let ast = parse(
             r#"
 func lag_day x = s"lag_day_todo({x})"
-func ret x = x / (lag_day x) - 1 + dividend_return
+func ret x dividend_return = x / (lag_day x) - 1 + dividend_return
```
Comment (max-sixty) [inline prql/src/semantic/materializer.rs:422]: I don't quite understand this change — `dividend_return` was supposed to be a column, rather than a param. Tell me if I'm missing something

File: prql/src/ast_fold.rs (hunk 1 above)
Comment (aljazerzen) [reply prql/src/ast_fold.rs:34]: Oh, forgot to tell you about that: I've changed that in a few places. It seemed better name, just because its shorter.

We should go over the project and refacator it everywhere

File: prql/src/semantic/materializer.rs (hunk 3 above)
Comment (aljazerzen) [reply prql/src/semantic/materializer.rs:422]: Functions cannot reference columns, because they could be used in different context, where that column would not be available.

Eg:
```
from employees
select first_name
derive [a: ret 15]   # there is only first_name in scope here, cannot reference dividend_return!
```

File: prql/tests/integration/compile.rs [hunk 4]
```diff
@@ -63,7 +63,7 @@ take 20
       title,
       country
     HAVING
-      ct > 200
+      COUNT(*) > 200
```
Comment (max-sixty) [inline prql/tests/integration/compile.rs:66]: I had thought we were getting `COUNT(*)` before actually. We can use `ct` here, which is slightly better, but either is totally fine.

Comment (aljazerzen) [reply prql/tests/integration/compile.rs:66]: No, I don't think either is fine.
For:
```sqlSELECT COUNT(*) AS ct
FROM employees
GROUP BY last_name
HAVING ct > 0
```
postgres returns `ERROR: column "ct" does not exist`

**Comment by max-sixty** [comment]
A good example of this:

```elm
from companies
select [name, company_no]
join employees [company_no]
```

previously compiled to

```sql
SELECT
  name,
  company_no
FROM
  companies
  JOIN employees USING(company_no)
```

...which is obv incorrect.

Now it compiles to:

```sql
SELECT
  companies.name,
  employees.*,
  company_no
FROM
  companies
  JOIN employees USING(company_no)
```

File: prql/tests/integration/compile.rs (hunk 4 above)
Comment (max-sixty) [reply prql/tests/integration/compile.rs:66]: Oh! You're right. Other DBs allow variables in `HAVING` and `ORDER BY`; I'm surprised postgres doesn't...

File: prql/src/ast_fold.rs (hunk 1 above)
Comment (max-sixty) [reply prql/src/ast_fold.rs:34]: I agree! 

https://en.wikipedia.org/wiki/Nominalization is impossible to stop!

File: prql/src/semantic/materializer.rs (hunk 3 above)
Comment (max-sixty) [reply prql/src/semantic/materializer.rs:422]: What do you think about "late binding" them? i.e. as though someone copy-pasted the function definition. In the way I was thinking about it, having:

```elm
from a
select (b / (lag_day b) - 1 + dividend_return)
```

..._would_ be allowed, and so having `ret b` would be equivalent to that.

I had thought of this as quite an important feature — otherwise functions can't be used to do things like "add X and subtract Y and multiply by Z" without specifying X & Y & Z each time.

I recognize that this sort of late-binding isn't common in languages; it's more like a macro. But also we're using `dividend_return` as more like another language would use `"dividend_return"` — i.e. if it's not specified as a parameter, then it's a column name, and can be treated as a literal.

Does my point make sense? WDYT?

Comment (aljazerzen) [reply prql/src/semantic/materializer.rs:422]: Our functions are very similar to macros, which is a case for this feature. I see the use case.

But, this kinda uncommon for other languages... I'm hesitant about this mostly because it breaks current resolver/materialiazer architecture. But to be honest, this would be useful to have.

Currently it can be bypassed by using s-strings, though.

Comment (max-sixty) [reply prql/src/semantic/materializer.rs:422]: Yes true re s-strings. 

Is it OK if I add an issue so we can track it?
