### PR TITLE
fix: anchoring of transitive deps of columns

### LINKED ISSUE #3347: PRQL generates nested window functions in window definitions
### What happened?

I was trying to help someone with a query that generates a running count of how long a streak of the same event is in a table. These kind of questions are usually really difficult to answer with SQL and I was hoping PRQL would come to the rescue here.

However my candidate query generates the following error, which I think comes from the DuckDB parser in the playground:

    Error: Parser Error: window functions are not allowed in window definitions

I believe the second `group + window` pipeline needs to flush the pipeline until that point into a CTE.

### PRQL input

```elm
from_text format:csv """
name,start_date,end_date,event_occurred
a,2023-06-19,2023-06-23,yes
a,2023-06-26,2023-06-30,yes
a,2023-07-03,2023-07-07,no
a,2023-07-10,2023-07-14,yes
a,2023-07-17,2023-07-21,yes
"""
sort {name, start_date}
derive {row = row_number this}
group {name, event_occurred} (
  sort start_date
  window (
    derive {grp = row - (row_number this)}
  )
)
group {grp} (
  sort start_date
  window (
    derive {count = row_number this}
  )
)
sort {name, start_date}
```

### SQL output

```SQL
WITH table_0 AS (
  SELECT
    'a' AS name,
    '2023-06-19' AS start_date,
    '2023-06-23' AS end_date,
    'yes' AS event_occurred
  UNION
  ALL
  SELECT
    'a' AS name,
    '2023-06-26' AS start_date,
    '2023-06-30' AS end_date,
    'yes' AS event_occurred
  UNION
  ALL
  SELECT
    'a' AS name,
    '2023-07-03' AS start_date,
    '2023-07-07' AS end_date,
    'no' AS event_occurred
  UNION
  ALL
  SELECT
    'a' AS name,
    '2023-07-10' AS start_date,
    '2023-07-14' AS end_date,
    'yes' AS event_occurred
  UNION
  ALL
  SELECT
    'a' AS name,
    '2023-07-17' AS start_date,
    '2023-07-21' AS end_date,
    'yes' AS event_occurred
)
SELECT
  name,
  start_date,
  end_date,
  event_occurred,
  ROW_NUMBER() OVER (
    ORDER BY
      name,
      start_date
  ) AS "row",
  ROW_NUMBER() OVER (
    ORDER BY
      name,
      start_date
  ) - ROW_NUMBER() OVER (
    PARTITION BY name,
    event_occurred
    ORDER BY
      start_date
  ) AS grp,
  ROW_NUMBER() OVER (
    PARTITION BY ROW_NUMBER() OVER (
      ORDER BY
        name,
        start_date
    ) - ROW_NUMBER() OVER (
      PARTITION BY name,
      event_occurred
      ORDER BY
        start_date
    )
    ORDER BY
      start_date
  ) AS count
FROM
  table_0
ORDER BY
  name,
  start_date

-- Generated by PRQL compiler version:0.9.3 (https://prql-lang.org)
```

### Expected SQL output

```SQL
WITH table_0 AS (
  SELECT
    *
  FROM
    (
      WITH table_0 AS (
        SELECT
          'a' AS name,
          '2023-06-19' AS start_date,
          '2023-06-23' AS end_date,
          'yes' AS event_occurred
        UNION
        ALL
        SELECT
          'a' AS name,
          '2023-06-26' AS start_date,
          '2023-06-30' AS end_date,
          'yes' AS event_occurred
        UNION
        ALL
        SELECT
          'a' AS name,
          '2023-07-03' AS start_date,
          '2023-07-07' AS end_date,
          'no' AS event_occurred
        UNION
        ALL
        SELECT
          'a' AS name,
          '2023-07-10' AS start_date,
          '2023-07-14' AS end_date,
          'yes' AS event_occurred
        UNION
        ALL
        SELECT
          'a' AS name,
          '2023-07-17' AS start_date,
          '2023-07-21' AS end_date,
          'yes' AS event_occurred
      )
      SELECT
        name,
        start_date,
        end_date,
        event_occurred,
        ROW_NUMBER() OVER (
          ORDER BY
            name,
            start_date
        ) AS "row",
        ROW_NUMBER() OVER (
          ORDER BY
            name,
            start_date
        ) - ROW_NUMBER() OVER (
          PARTITION BY name,
          event_occurred
          ORDER BY
            start_date
        ) AS grp
      FROM
        table_0
    )
),
with_groups AS (
  SELECT
    *
  FROM
    table_0
)
SELECT
  *,
  ROW_NUMBER() OVER (
    PARTITION BY grp
    ORDER BY
      start_date
  ) AS count
FROM
  with_groups
ORDER BY
  name,
  start_date

-- Generated by PRQL compiler version:0.9.3 (https://prql-lang.org)
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

### Anything else?

Off topic but useful little lifehack to produce the expected output:

Take the output from the first part of the PRQL query that you want to be wrapped in a CTE and put it in an s-string and then you can apply the remaining PRQL query to that. That's how I generated the expected SQL output above, from the following PRQL query:

```prql
let with_groups = from s"""SELECT * FROM (
WITH table_0 AS (
  SELECT
    'a' AS name,
    '2023-06-19' AS start_date,
    '2023-06-23' AS end_date,
    'yes' AS event_occurred
  UNION
  ALL
  SELECT
    'a' AS name,
    '2023-06-26' AS start_date,
    '2023-06-30' AS end_date,
    'yes' AS event_occurred
  UNION
  ALL
  SELECT
    'a' AS name,
    '2023-07-03' AS start_date,
    '2023-07-07' AS end_date,
    'no' AS event_occurred
  UNION
  ALL
  SELECT
    'a' AS name,
    '2023-07-10' AS start_date,
    '2023-07-14' AS end_date,
    'yes' AS event_occurred
  UNION
  ALL
  SELECT
    'a' AS name,
    '2023-07-17' AS start_date,
    '2023-07-21' AS end_date,
    'yes' AS event_occurred
)
SELECT
  name,
  start_date,
  end_date,
  event_occurred,
  ROW_NUMBER() OVER (
    ORDER BY
      name,
      start_date
  ) AS "row",
  ROW_NUMBER() OVER (
    ORDER BY
      name,
      start_date
  ) - ROW_NUMBER() OVER (
    PARTITION BY name,
    event_occurred
    ORDER BY
      start_date
  ) AS grp
FROM
  table_0
)
"""
from with_groups
group {grp} (
  sort start_date
  window (
    derive {count = row_number this}
  )
)
sort {name, start_date}
```

### PR DESCRIPTION
**Pull request by aljazerzen**
Closes #3347

### CODE REVIEW

File: prqlc/prql-compiler/tests/sql/sql.rs [hunk 1]
```diff
@@ -1116,6 +1116,35 @@ fn test_window_functions_12() {
...
+        ROW_NUMBER() OVER (PARTITION BY album_id) AS _expr_0
+      FROM
+        tracks
+    )
+    SELECT
+      *,
+      milliseconds - _expr_0 AS grp,
+      ROW_NUMBER() OVER (PARTITION BY milliseconds - _expr_0) AS count
+    FROM
+      table_0
```
Comment (max-sixty) [inline prqlc/prql-compiler/tests/sql/sql.rs:1144]: This looks great!

**Review by max-sixty — APPROVED** [review]
Thanks!
