### PR TITLE
fix: Add support for expressions on left hand side of std.in operator

### LINKED ISSUE #4497: std.in operator does not support expression on left-hand-side
### What happened?

I'm trying to make a generic "boolean" conversion function, and this is where I am starting:

```
let coalesce_bool = func
  val <scalar || null>
  -> case [
    val == null => null,
    val == 0 => false,
    val == 1 => true,
    (val | in ["no", "n", "N", "false"]) => false,
    (val | in ["yes", "y", "Y", "true"]) => true,
  ]
```

This is working well, for example in the following:

```
from [{foo = 1}, {foo = null}]
derive { foo_b = coalesce_bool foo }
```

However, feeding a numeric value other than 0 or 1 into the function is causing DuckDB to raise a Conversion Error ("Could not convert string 'no' to INT32). This is because DuckDB gets to the corresponding line in the CASE statement

```
    WHEN foo IN ('no', 'n', 'N', 'false') THEN false
```

and tries to cast the strings in the array to numbers.

The solution for me seemed simple -- to cast `val` to VARCHAR to do the comparison by strings:

```
let coalesce_bool = func
  val <scalar || null>
  -> case [
    val == null => null,
    val == 0 => false,
    val == 1 => true,
    (val | as VARCHAR | in ["no", "n", "N", "false"]) => false,
    (val | as VARCHAR | in ["yes", "y", "Y", "true"]) => true,
  ]
```

but this causes a PRQL compiler panic:

```
The application panicked (crashed).
Message:  args to `std.array_in` must be a column ref and an array
Location: prqlc/prqlc/src/sql/gen_expr.rs:176

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 13 frames hidden ⋮                              
  14: prqlc::sql::gen_expr::process_array_in::h96ab7dc44c311876
      at /Users/kgutwin/github/prql/prqlc/prqlc/src/sql/gen_expr.rs:176
  15: prqlc::sql::gen_expr::translate_expr::h392231bd9a27822a
      at /Users/kgutwin/github/prql/prqlc/prqlc/src/sql/gen_expr.rs:106
[ ... snip ... ]
```

I looked at [prqlc/prqlc/src/sql/gen_expr.rs](https://github.com/PRQL/prql/blob/5ccb89c430721e68bb9db0475ef94266d83d7cf1/prqlc/prqlc/src/sql/gen_expr.rs#L176) and it's not obvious to me why there's a panic there, especially as the other `process_*()` functions seem to handle left-hand-side expressions easily. Would it be possible to remove this panic in order to support more complex expressions for the `std.in` function? Or is there an underlying reason why the IN operator needs to have a column reference only on the left-hand side?

### PRQL input

```elm
from [{ a = 1 }]
derive { b = ( a+1 | in [2, 3] ) }
```

### SQL output

```SQL
n/a (compiler crashes)
```

### Expected SQL output

```SQL
WITH table_0 AS (
  SELECT
    1 AS a
)
SELECT
  a,
  a + 1 IN (2, 3) AS b
FROM
  table_0
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kgutwin**
Resolves #4497.

I'm hoping this is as simple as it needs to be to resolve this... if there's a more complex reason why `std.in` needs to not support expressions on the left-hand side, more discussion is appreciated!

Thanks for this package - it's making a big impact on our project, which we hope to release relatively soon!

### CODE REVIEW

**Comment by max-sixty** [comment]
@kgutwin very nice fix!

Merging now — lmk if you want a release soon, was planning to do one in a few days, can push up if needed.

Great if you can add a changelog in another PR, no stress tho

**Comment by max-sixty** [comment]
(+ if you can run `cargo fmt` then great, otherwise I can)

File: prqlc/prqlc/tests/integration/sql.rs [hunk 1]
```diff
@@ -1155,6 +1155,8 @@ fn test_in_values_01() {
     from employees
     filter (title | in ["Sales Manager", "Sales Support Agent"])
     filter (employee_id | in [1, 2, 5])
+    filter (f"{emp_group}.{role}" | in ["sales_ne.mgr", "sales_mw.mgr"])
+    filter (s"{metadata} ->> '$.location'" | in ["Northeast", "Midwest"])
```
Comment (PrettyWood) [inline prqlc/prqlc/tests/integration/sql.rs:1159]:
```suggestion
    filter (s"{metadata} -> '$.location'" | in ["Northeast", "Midwest"])
```
?

Comment (max-sixty) [reply prqlc/prqlc/tests/integration/sql.rs:1159]: Ah, good point. 

I thought the tests had passed, but actually the `cargo fmt` test failed before these had a chance to run. So when we fix `fmt`, we'll get to test this properly.

It will need a run of `task test-rust` to update the snapshots (or `cargo insta test --accept --features=default,test-dbs`)

Comment (kgutwin) [reply prqlc/prqlc/tests/integration/sql.rs:1159]: @PrettyWood I think `->>` is the right operator here, since `in ["", ...]` is comparing to a VARCHAR which is what `->>` returns. Reference: https://duckdb.org/docs/extensions/json.html#json-extraction-functions

Comment (max-sixty) [reply prqlc/prqlc/tests/integration/sql.rs:1159]: Don't need to delay merging, but FYI adding this to a query in this path https://github.com/PRQL/prql/blob/76c4f767c4312976dba0fbadfa6c27b84e31faa9/prqlc/prqlc/tests/integration/queries/cast.prql would test on duckdb & postgres DBs in CI

File: prqlc/prqlc/src/sql/gen_expr.rs [hunk 2]
```diff
@@ -173,7 +178,10 @@ fn process_array_in(args: &[Expr], ctx: &mut Context) -> Result<sql_ast::Expr> {
                 .collect::<Result<Vec<sql_ast::Expr>>>()?,
             negated: false,
         }),
-        _ => panic!("args to `std.array_in` must be a column ref and an array"),
+        _ => Err(
+            Error::new_simple("args to `std.array_in` must be an expression and an array")
```
Comment (max-sixty) [inline prqlc/prqlc/src/sql/gen_expr.rs:182]:
```suggestion
            Error::new_simple("args to `std.array_in` must be an expression and an array respectively")
```

**Comment by max-sixty** [comment]
Thanks @kgutwin !
