### PR TITLE
fix(prql-compiler): allow `SELECT\n` in s-strings representing a table

### LINKED ISSUE #2430: Problem with parsing s-string in `from`?
### What happened?

```elm
let _tab0 = s"""
  SELECT foo
  FROM bar
"""

from _tab0
```

The above PRQL is processed successfully, but the following PRQL with added newlines seems to cause an error.

### PRQL input

```elm
let _tab0 = s"""
  SELECT
    foo
  FROM bar
"""

from _tab0
```

### SQL output

```SQL
None
```

### Expected SQL output

```SQL
WITH table_0 AS (
  SELECT
    foo
  FROM
    bar
),
_tab0 AS (
  SELECT
    *
  FROM
    table_0 AS table_1
)
SELECT
  *
FROM
  _tab0
```

### MVCE confirmation

- [x] Minimal example
- [x] New issue

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by eitsupi**
Fix #2430

### CODE REVIEW

File: prql-compiler/src/sql/gen_expr.rs [hunk 1]
```diff
@@ -400,13 +400,14 @@ pub(super) fn translate_query_sstring(
 ) -> Result<sql_ast::Query> {
     let string = translate_sstring(items, context)?;
 
+    let re = Regex::new(r"(?i)^SELECT(\s|\n|\r)").unwrap();
```
Comment (max-sixty) [inline prql-compiler/src/sql/gen_expr.rs:403]: FYI this can be `r"(?i)^SELECT\b"`

**Comment by max-sixty** [comment]
Thanks!

File: prql-compiler/src/sql/gen_expr.rs (hunk 1 above)
Comment (eitsupi) [reply prql-compiler/src/sql/gen_expr.rs:403]: Thanks for pointing that, I didn't know `\b`...
I will open another PR.
