### PR TITLE
Fix string escapes, refactor

### LINKED ISSUE #440: Escape single quote characters in strings
Following up to https://github.com/prql/prql/pull/439, Currently

```elm
derive x: "two households'"
```

compiles to:

```sql
SELECT
  ' two households ' '' AS x
```

Whereas I think it should compile to:

```sql
SELECT
  'two households\'' AS x
```

I'm actually not sure why it has spaces around it, and where `' ''` is coming from.

### PR DESCRIPTION
**Pull request by aljazerzen**
Closes #440

### CODE REVIEW

File: prql-compiler/src/sql/translator.rs [hunk 1]
```diff
@@ -1438,4 +1437,40 @@ take 20
...
+            y = 'two households"',
+            z = f"a {x} b' {y} c",
+            v = f'a {x} b" {y} c',
+        ]
+        "###,
+        )?;
+
+        assert_display_snapshot!((resolve_and_translate(query)?), @r###"
+        SELECT
+          'two households''' AS x,
```
Comment (max-sixty) [inline prql-compiler/src/sql/translator.rs:1456]: FWIW I'm not sure this is quite right. At least it doesn't compile on BigQuery. (not saying it's on you, tbc) 
image

**Comment by aljazerzen** [comment]
Indeed, the "two single quotes" escaping only works for [Oracle, SQL Server, MySQL and PostgreSQL](https://www.databasestar.com/sql-escape-single-quote/).

BQ uses [backslash escaping](https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical) and also some other approaches.

Currently we cannot produce anything other the "two single quotes" escaping, because sqlparser does not support it (see `sqlparser::ast::value:183`). We will need a hack on out side or a PR on sqlparser.

**Comment by max-sixty** [comment]
Ah great, TIL!

Yeah, it's a shame BQ isn't supported by sqlparser. It's nice to test because it's very easy to open a browser tab, but probably we need to use sql fiddle in these cases.
